R/import.R, R/spec.R, R/time.R, R/validate.R
With this PR, dates in calendar.txt, calendar_dates.txt and feed_info.txt are read with `lubridate::date`. The gtfs specification states that dates have to be provided as YYYYMMDD and I'd say reading them as dates instead of characters makes further data analysis easier.
There are two new helper methods in time.R
- `set_date_service_table(gtfs_obj)` adds a data frame to the gtfs object that stores which services run on which dates. The resulting `gtfs_obj$date_service` looks like this.
```
date       service_id
<date>     <chr>     
1 2017-12-11 b07sy  
2 2017-12-11 b0nbk  
3 2017-12-11 b0nbn  
4 2017-12-12 a0nbx  
5 2017-12-12 a0nc7  
```
This can then be used to analyse the dates with most services and trips (e.g. by joining tables and using summary).
- `set_hms_times(gtfs_obj)` adds …
=> Read feed with lubridate::date

DESCRIPTION, R/time.R, tests/testthat/test-time.R
Sorry for the kinda erratic development but I had to revisit #26. Apparently tidyverse functions don't work with lubridate ([see github issue](https://github.com/tidyverse/dplyr/issues/2432)). That's why I changed the implementation of `set_hms_times` to work with `hms::hms`. That way, joining and otherwise filtering tables seems to work. The time functions of lubridate would've been a bit overkill anyways, since we don't have to work with timezones and so on.
Maybe more important: There's now tests covering the two methods added in #26. I also fixed a bug with date ranges.
=> Switch from lubridate to hms

R/import.R, R/spec.R, tests/testthat/test-import-gtfs.R, tests/testthat/test-main.R
With this PR, the test files use the fixed sample feed within the repository (see #37). The examples also refer to that feed. Plus, I re-added min_transfer_time as integer (lost pr #31) and cleaned up spec.R by removing service_name and exception_type (for transfers).
=> Use test feed on repository

R/import.R, tests/testthat/test-import-gtfs.R
This PR slightly changes how local files are read. I often download feeds outside of R and I always found `gtfs <- read_gtfs("/path/to/feed.zip", T)` inconvenient. So I'd suggest that read_gtfs checks if the path is a url and then proceeds to download. If not, no error is thrown and the path is considered a local path. The `local = FALSE` default parameter still exists and read_gtfs shouldn't behave differently for current users. Even though I'd say we could get rid of the param quite easily.
=> Try url then local path

R/utils.R
Deprecation message: "zip::zip() is deprecated, please use zip::zipr() instead". Also fixes some bugs with write_gtfs on my computer, don't know how widespread these are.
=> Use zipr() instead of zip() in write_gtfs

R/raptor.R, tests/testthat/test-raptor.R
Number of transfers (now starting with 0) is calculated anyways, might as well return them for `raptor` and `travel_times`.
=> return number of transfers

DESCRIPTION
I think we need "GTFS" explicitly in the package title otherwise people [might not find the package](https://rdrr.io/find/?repos=cran%2Cbioc%2Crforge%2Cgithub&fuzzy_slug=gtfs).
=> update package title

R/raptor.R, man/raptor.Rd, man/travel_times.Rd, tests/testthat/test-raptor.R
Closes #112 
`raptor` is the "lower level" implementation and still returns data.tables
=> travel_time() returns tibble by default

R/raptor.R, man/filter_stop_times.Rd, man/get_feedlist.Rd, man/raptor.Rd, man/read_gtfs.Rd, man/travel_times.Rd, tests/testthat/test-raptor.R
With this PR, `raptor` considers transfers from `from_stop_id` on the minimal departure time instead of the time of the first actual departure in stop_times. Everything else, especially departure time range behavior, stays the same.
=> Earlier transfers from from_stops

R/spec.R
Two new files, [translations.txt and attributions.txt](https://developers.google.com/transit/gtfs/reference#translationstxt) have been added to the GTFS reference (don't know when though). I haven't really come across them in real feeds though.
=> update spec (translations and attributions)

R/spatial.R
potentially wrong shape ids are returned from the function shapes_as_sf (e.g. Berlin GTFS Feed).
unique(gtfs_shapes$shape_id) does not necessarily have the same order of shape ids (because of the split function in line 49).
Instead: use names(list_of_line_tibbles)
=> bug fix: wrong shape ids in shapes_as_sf

R/raptor.R, man/filter_stop_times.Rd, man/raptor.Rd, man/travel_times.Rd, tests/testthat/test-raptor.R
With this pull request it's now possible to calculate travel times for _incoming_ journeys by using the new parameter `arrival=TRUE`. This is done by "reversing" stop_times internally. It's now also possible to keep the latest arriving journey with `keep="latest"`.  This allows to answer questions like "who can reach this location before 8 am with at most 30 minutes of traveling". Previously, `raptor` and `travel_times` could only calculate journeys departing from a stop. 
There are some breaking changes, the following parameters have been renamed:
- `from_stop_id` changed to `stop_id`
- `from_stop_name` changed to `stop_name`
- `departure_time_range` changed to `time_range`
The column names of the returned tables have been changed:
- `min_arrival_time` to `journey_arrival_time`
- …
=> Travel times for incoming journeys

.travis.yml, R/utils.R, man/write_gtfs.Rd, tests/testthat/test-utils.R
With this PR, write_gtfs can write a feed to a directory which makes data transfer with other programs easier if necessary. In addition, NA values are written as empty csv cells.
=> Write_gtfs to directory

.github/workflows/R-CMD-check.yaml, .github/workflows/test-coverage.yaml
Many folk including myself are finding github actions pretty impressive for a range of standard CI tasks. This PR adds a matrix workflow for `R CMD check` on a host of OSs, along with a test coverage workflow, essentially copied straight from my workflow files for `gtfsrouter`. You can see the typical output for that repo [here](https://github.com/ATFutures/gtfs-router/actions). No worries if you'd prefer not to merge this PR, but I just thought it might help.
=> add github workflows

R/raptor.R
Small optimiziation for `filter_stop_times`, reduces run time for a large feed (`stop_times` with 11 million rows) by ~40%.
=> optimize filter_stop_times

R/spatial.R, R/time.R, R/utils.R
This PR makes your package compatible with the next version of dplyr:
The join functions in dplyr (like `left_join()`) now return a warning by default when a row in `x` matches _multiple_ rows in `y`. While this is typical SQL behavior, it is often unexpected during data analysis (many people don't even know it is possible), so we've decided to make this a warning. In dplyr 1.1.0, you silence this warning with `multiple = "all"`. In the meantime, to be compatible with both dev and CRAN dplyr we need to work around broken tests of yours that were expecting no warnings. I've done that by suppressing the warnings in the join calls that caused errors. You can switch to explicitly setting `multiple = "all"` instead after the dplyr 1.1.0 release, but this should work for both dev and CRAN dplyr …
=> Suppress multiple match warning

DESCRIPTION, tests/testthat/test-read-gtfs.R
Should close #193 
I think the "multiple match" issue arose because dplyr was updated to v1.1 yesterday. There's still some code linked to dplyr 1.1 (see #191) but I'd tackle this with the next release.
=> Use expect_no_warning, remove httr dependency

DESCRIPTION, R/validate_gtfs.R
As it turns out, the implemented check for duplicated primary keys is _very_ slow on larger feeds. This PR improves the runtime by about 10x (!) by using `data.table::anyDuplicated`. Example benchmarks:
With the NYC dataset 
```r
nyc = gtfsio::import_gtfs(system.file("extdata", "google_transit_nyc_subway.zip", package = "tidytransit"))
duplicated_primary_keys(nyc)
```
```
Unit: milliseconds
expr       min       lq      mean    median        uq      max neval
old 531.28157 624.1847 673.41524 696.80770 714.99092 763.3479    20
new  26.70495  30.0662  43.68424  33.98627  46.30624 106.0321    20
```
With the [Swiss dataset](https://opentransportdata.swiss/en/dataset/timetable-2023-gtfs2020):
```
Unit: seconds
expr       min        lq      mean    median        uq       max neval
old 16.113029 …
```
=> Improve duplicated primary key check

DESCRIPTION, R/spatial.R
I think it's safe to bump the dplyr version and remove the hotfix introduced in #197
=> depend on dplyr >= 1.1.1

R/spec.R
`fare_products` SPEC is missing `fare_media_id` as described in GTFS Specification. 
https://gtfs.org/schedule/reference/#fare_productstxt
=> fix: Add `fare_media_id` to `fare_products` in spec.R

R/dates.R, R/service.R, tests/testthat/test-frequencies.R, tests/testthat/test-raptor.R, tests/testthat/test-travel_times.R, vignettes/frequency.Rmd, vignettes/servicepatterns.Rmd, vignettes/timetable.Rmd
While preparing for the release I noticed some partial argument matching issues which _might_ lead to bugs. AFAIK there's no easy way to spot them, I just set this
```r
options(warnPartialMatchArgs = TRUE)
options(warnPartialMatchDollar = TRUE)
options(warnPartialMatchAttr = TRUE)
options(warn = 2)
```
in my `.Rprofile` and then sourced the tests manually, knitted the vignettes and ran `devtools::run_examples(run_donttest = TRUE, run_dontrun = TRUE)`.
=> Fix partial matching issues
